// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_yQXazYjjgSpQUN6LmwhfvpNDRdJxK2w',
    appId: '1:961998658534:web:9fc99d420324e24c60d427',
    messagingSenderId: '961998658534',
    projectId: 'zerasfood',
    authDomain: 'zerasfood.firebaseapp.com',
    storageBucket: 'zerasfood.firebasestorage.app',
    measurementId: 'G-HPLR3Q6H4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJTdLEAVwKmOy3Vie_WBNjD2Lf3_YYlAU',
    appId: '1:961998658534:android:b7dce2570bf473e460d427',
    messagingSenderId: '961998658534',
    projectId: 'zerasfood',
    storageBucket: 'zerasfood.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKf9YAi6BiG9rDtRuqeh-_IahfKX5fHkw',
    appId: '1:961998658534:ios:564316c71d5f06eb60d427',
    messagingSenderId: '961998658534',
    projectId: 'zerasfood',
    storageBucket: 'zerasfood.firebasestorage.app',
    iosBundleId: 'com.example.zerasfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKf9YAi6BiG9rDtRuqeh-_IahfKX5fHkw',
    appId: '1:961998658534:ios:564316c71d5f06eb60d427',
    messagingSenderId: '961998658534',
    projectId: 'zerasfood',
    storageBucket: 'zerasfood.firebasestorage.app',
    iosBundleId: 'com.example.zerasfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_yQXazYjjgSpQUN6LmwhfvpNDRdJxK2w',
    appId: '1:961998658534:web:092ebfcf269b803560d427',
    messagingSenderId: '961998658534',
    projectId: 'zerasfood',
    authDomain: 'zerasfood.firebaseapp.com',
    storageBucket: 'zerasfood.firebasestorage.app',
    measurementId: 'G-TYNWD39MET',
  );
}
